x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:9196/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},d{3}) (?P<message>(?s:.*))$$'

version: "3.4"

services:
  loki:
    image: grafana/loki:2.8.3
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "9196:9196"

  app-a:
    build: ./fastapi_app/
    ports:
      - "9193:9193"
    depends_on:
      - loki
    environment:
      APP_NAME: "app-a"
    logging: *default-logging

  app-b:
    build: ./fastapi_app/
    ports:
      - "9194:9193"
    depends_on:
      - loki
    environment:
      APP_NAME: "app-b"
    logging: *default-logging

  app-c:
    build: ./fastapi_app_plain/
    ports:
      - "9195:9193"
    depends_on:
      - loki
    environment:
      APP_NAME: "app-c"
      OTEL_PYTHON_LOG_CORRELATION: "true"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo:4317"
      OTEL_METRICS_EXPORTER: "none"
      OTEL_SERVICE_NAME: "app-c"
      OTEL_RESOURCE_ATTRIBUTES: "compose_service=app-c"
    command: "opentelemetry-instrument python main.py"
    logging: *default-logging

  prometheus:
    image: prom/prometheus:v2.45.0
    ports:
      - "9197:9197"
    volumes:
      - ./etc/prometheus:/workspace
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    logging: *default-logging

  tempo:
    image: grafana/tempo:2.1.1
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "9198:9198"
    depends_on:
      - loki
    logging: *default-logging

  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "9199:9199"
    volumes:
      - ./etc/grafana/:/etc/grafana/provisioning/datasources
      - ./etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    logging: *default-logging
